export const data = [
  {
    adult: false,
    backdrop_path: "/y5Z0WesTjvn59jP6yo459eUsbli.jpg",
    id: 663712,
    original_language: "en",
    original_title: "Terrifier 2",
    overview: "",
    poster_path: "/b6IRp6Pl2Fsq37r9jFhGoLtaqHm.jpg",
    release_date: "2022-10-06",
    title: "테리파이어 2",
    vote_average: 7.1,
  },
  {
    adult: false,
    backdrop_path: "/askg3SMvhqEl4OL52YuvdtY40Yb.jpg",
    id: 354912,
    original_title: "Coco",
    overview:
      "미구엘은 멕시코의 자랑인 에르네스토 델라 크루즈 같은 뮤지션이 되길 꿈꾸지만 미구엘 집안 사람들에게 음악은 금기다. 먼 옛날 조상 중에 음악 때문에 가족을 버린 인물이 있었기 때문. 미구엘은 죽은 자의 날이 되자 실력으로 인정받겠다는 결심을 하고 경연 무대에 오르려 하는데, 우연히 에르네스토의 기타에 손을 댔다가 죽은 자들의 세상에 들어서게 된다. 이승과 저승을 이어주는 마리골드 꽃길을 건너 죽은 자들의 세상에 도착한 미구엘은 거짓말과 위변조가 장기인 헥터를 만난다. 그리고 꿈에 그리던 우상 에르네스토를 만나러 가는 여정에서 가족의 비밀을 알게 된다.",
    popularity: 3795.511,
    poster_path: "/6AANwKhjIEVyya95oW4IA6joL1Z.jpg",
    release_date: "2017-10-27",
    title: "코코",
    vote_average: 8.2,
  },
  {
    adult: false,
    backdrop_path: "/naNXYdBzTEb1KwOdi1RbBkM9Zv1.jpg",
    id: 420634,
    original_language: "en",
    original_title: "Terrifier",
    overview:
      "할로윈 밤. 술마시고 진탕 놀다 귀가하던 타라와 돈은 광대 복장의 남자와 맞닥뜨린다. 이들은 할로윈 코스프레를 한 찌질남으로 치부하지만, 그는 수년 전 세상을 떠들썩하게 만든 광대 살인마였고 할로윈 밤에 다시 돌아온 것이었다. 두 사람은 광대 살인마의 표적이 되는데...",
    poster_path: "/6PQqC4SbY910VvyVad6mvsboILU.jpg",
    release_date: "2016-10-15",
    title: "테리파이어",
    vote_average: 6.5,
  },
  {
    adult: false,
    backdrop_path: "/pGx6O6IwqADOsgmqWzPysmWnOyr.jpg",
    id: 732459,
    original_language: "en",
    original_title: "Blade of the 47 Ronin",
    overview: "",
    poster_path: "/kjFDIlUCJkcpFxYKtE6OsGcAfQQ.jpg",
    release_date: "2022-10-25",
    title: "Blade of the 47 Ronin",
    vote_average: 7.2,
  },
  {
    adult: false,
    backdrop_path: "/tIX6j3NzadlwGcJ52nuWdmtOQkg.jpg",
    id: 717728,
    original_title: "Jeepers Creepers: Reborn",
    overview: "",
    poster_path: "/aGBuiirBIQ7o64FmJxO53eYDuro.jpg",
    release_date: "2022-09-15",
    title: "Jeepers Creepers: Reborn",
    vote_average: 5.7,
  },
  {
    adult: false,
    backdrop_path: "/iS9U3VHpPEjTWnwmW56CrBlpgLj.jpg",
    id: 642885,
    original_title: "Hocus Pocus 2",
    overview:
      "누군가가 검은 불꽃 초에 불을 붙여 17세기에 활동했던 자매들을 되살린 지도 29년이 흘렀다. 이제 자매들은 원수를 갚으려 한다. 핼러윈 전날의 동이 터오기 전에 세일럼에서 대혼란을 일으키려는 마녀들을 막아설 사람은 세 고등학생뿐이다.",
    poster_path: "/xpDdvIaTHn38F17pPseL1MQI05B.jpg",
    release_date: "2022-09-27",
    title: "호커스 포커스 2",
    vote_average: 7.6,
  },
  {
    adult: false,
    backdrop_path: "/1DBDwevWS8OhiT3wqqlW7KGPd6m.jpg",
    original_title: "Fall",
    overview:
      "내려갈 길이 끊겨버린 600미터 TV 타워 위에서  두 명의 친구가 살아남기 위해 펼치는 사상 최초의 고공 서바이벌 여기에서",
    popularity: 1888.082,
    poster_path: "/8huJowZK1t7MNLEKo3dgLAxmiLW.jpg",
    release_date: "2022-08-11",
    title: "폴: 600미터",
    vote_average: 7.3,
  },
  {
    adult: false,
    backdrop_path: "/etP5jwlwvkNhwe7jnI2AyA6ZKrR.jpg",
    id: 575322,
    original_title: "Звёздный разум",
    overview:
      "치명적인 바이러스로 지구의 식물들이 파괴된 지 3년 후 산소가 부족해지고 과학자들은 전 인류를 구하기 위해 새로운 행성을 찾는 미션을 받고 우주로 떠난다. 하지만, 우주선은 입력한 궤도와는 전혀 다른 방향으로 이끌려가 알 수 없는 행성에 고립되고 비행 멤버들은 상상할 수 없는 존재로부터 공격을 받기 시작하는데…!",
    poster_path: "/iVwd4NKcvWIfxP36DsCBHd7lqEE.jpg",
    release_date: "2022-01-06",
    title: "제미나이: 지구 최후의 날",
    vote_average: 5.6,
  },
  {
    adult: false,
    backdrop_path: "/5GA3vV1aWWHTSDO5eno8V5zDo8r.jpg",
    id: 760161,
    original_title: "Orphan: First Kill",
    overview:
      "엄청난 비밀을 숨긴 사이코패스가 에스토니아의 정신병동을 탈출, 부유한 가족의 실종된 딸 ‘에스더’로 사칭해 미국에 온다. 재회의 기쁨도 잠시, 어딘지 낯선 딸의 정체를 눈치챈 엄마는 가족을 지키기 위해 에스더와 맞서는데...  누구도 상상 못한 충격적인 반전이 기다린다!",
    poster_path: "/vKIhsEVEtLTwTkmLSDNi230Zr3Q.jpg",
    release_date: "2022-07-27",
    title: "오펀: 천사의 탄생",
    vote_average: 6.8,
  },
  {
    adult: false,
    backdrop_path: "/aTovumsNlDjof7YVoU5nW2RHaYn.jpg",
    id: 616820,
    original_title: "Halloween Ends",
    overview:
      "4년 전 또 한번 할로윈의 악몽을 겪은 뒤 조용한 일상을 보내고 있는 ‘로리 스트로드’와 손녀 ‘앨리슨’.  어느 날 ‘앨리슨’은 베이비시터 살인자로 낙인 찍힌 ‘코리’와 만나게 되고 이 둘은 급격히 가까워진다.  하지만 ‘코리’에게서 ‘마이클 마이어스’와 같은 어두운 면모를 발견한 ‘로리 스트로드’는  그에게 ‘앨리슨’과 멀어지라고 경고한다.  이후 해든필드에 끔찍한 살인 사건이 벌어지면서 ‘마이클 마이어스’가 돌아왔다는 소문이 퍼지기 시작하고  ‘로리 스트로드’는 이제 그와의 악연을 끊어내려 하는데…",
    poster_path: "/1ScxCajFdgMNWBn9BuFlB4sMTAJ.jpg",
    release_date: "2022-10-12",
    title: "할로윈 엔드",
    vote_average: 6.6,
  },
  {
    adult: false,
    backdrop_path: "/bJa3RcFKgtVKJqTJCSSuBQeP9c8.jpg",
    id: 86328,
    original_title: "Terrifier",
    overview: "",
    poster_path: "/gb6rq2nD0jRrN0dCzigg2MxXNsB.jpg",
    release_date: "2011-08-09",
    title: "테리파이어",
    video: false,
    vote_average: 6.8,
  },
  {
    adult: false,
    backdrop_path: "/5hoS3nEkGGXUfmnu39yw1k52JX5.jpg",
    id: 960704,
    original_title: "鋼の錬金術師 完結編 最後の錬成",
    overview:
      "엘릭 형제의 길고 파란만장했던 여정, 그 종지부를 찍을 완결편 2부작의 마지막 작품. 에드워드와 알폰스가 국가 전체를 뒤흔들 초월적인 위협에 맞선다.",
    poster_path: "/qJD1kg5vrKKllZaZWyELVdxdbid.jpg",
    release_date: "2022-06-24",
    title: "강철의 연금술사 완결편: 최후의 연성",
    vote_average: 6.2,
  },
  {
    adult: false,
    backdrop_path: "/mMA2YNddowV8MZtxpbn0a7Yilum.jpg",
    id: 928123,
    original_title: "长津湖之水门桥",
    overview: "",
    poster_path: "/ugiL6wIhl1OfPyv1gqLkTe45jLl.jpg",
    release_date: "2022-02-01",
    title: "장진호지수문교",
    vote_average: 6.4,
  },
];
